project_id = "tjotexujwnfltszqqovk"

[functions.article-share]
verify_jwt = false

[functions.soccer-chat]
verify_jwt = false

[functions.football-news]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.translate-article]
verify_jwt = false

[functions.translate-all-languages]
verify_jwt = false

[functions.og-image]
verify_jwt = false
